version: '3.3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
       - --api.dashboard=true
       - --providers.docker=true        
- --providers.docker.network=web
       - --entrypoints.web.address=:80
       - --entrypoints.web-secured.address=:443 
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443" # <== https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.monitor.rule=Host(`monitor.stevenkerautret.eu`)
      - traefik.http.routers.monitor.tls=true
      - traefik.http.routers.monitor.service=api@internal
      - traefik.http.routers.monitor.tls.certresolver=mytlschallenge
    restart : always

fastapi:
    container_name: fastapi
    ports:
      - '6000:80'
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    volumes:
      - './app:/app'
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-web.entrypoints=web"
      - "traefik.http.routers.fastapi-web.middlewares=redirect@file"
      - "traefik.http.routers.fastapi-secured.entrypoints=web-secured"
      - "traefik.http.routers.fastapi-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.fastapi-web.rule=Host(`fastapi.stevenkerautret.eu`)"
      - "traefik.http.routers.fastapi-secured.rule=Host(`fastapi.stevenkerautret.eu`)"

networks:
  web:
    external: true
  backend:
    external: false
